### ISSUE TITLE
Double build on pull request

### ISSUE THREAD

**Issue by LoDThe** [hse-tex/hse-tex#159]
Когда мэинтейнеры репозитория что-то коммитят в пулл реквест, билд триггерится два раза ([пример](https://github.com/hse-tex/hse-tex/pull/158)):
1. На push
2. На pull request

Надо бы сделать, чтобы билд происходил только один раз. Например, указать только интересующие нас ветки:
```
on:
  push:
    branches:
      - master
      - gh-pages
  pull_request:
    branches:
      - master
```
